FROM ruby:3.0.4

WORKDIR /app

RUN apt-get update && apt-get install -y dnsutils iproute2
RUN gem install bundler:2.3.16

COPY Gemfile* /app/
RUN bundle install

COPY . /app/

EXPOSE 3000
CMD rm -f tmp/pids/server.pid; ./bin/dev
