FROM ruby:3.0.4

WORKDIR /app

RUN apt-get update
RUN gem install bundler:2.3.16

RUN bundle config set without 'development test'
ENV RAILS_ENV production
ENV RAILS_SERVE_STATIC_FILES true
ENV RAILS_LOG_TO_STDOUT true

COPY Gemfile* /app/
RUN bundle install

COPY . /app/

ARG RAILS_MASTER_KEY
RUN bundle exec rake assets:precompile

EXPOSE 3000

CMD rm -f tmp/pids/server.pid; bundle exec rails server -b 0.0.0.0
